# Preprocessing Data

## Processing a raw data given a rules

In [477]:
import numpy as np

In [478]:
np.set_printoptions(suppress=True , linewidth=100, precision=2)

> Suppress is for disable a simplified out of bonds digit like `123e+`
<br>
> Linewidth is t set a width in a roow to a `100`
<br>
> Precision is used for a display 2 digit decimalals

### Loading a csv data and generate it using `genfromtxt`

In [479]:
pre_data = "dataset/loan-data.csv"

In [480]:
raw_data = np.genfromtxt(pre_data, delimiter=';', encoding='latin1')
raw_data

array([[        nan,         nan,         nan, ...,         nan,         nan,         nan],
       [48010226.  ,         nan,    35000.  , ...,         nan,         nan,     9452.96],
       [57693261.  ,         nan,    30000.  , ...,         nan,         nan,     4679.7 ],
       ...,
       [50415990.  ,         nan,    10000.  , ...,         nan,         nan,     2185.64],
       [46154151.  ,         nan,         nan, ...,         nan,         nan,     3199.4 ],
       [66055249.  ,         nan,    10000.  , ...,         nan,         nan,      301.9 ]])

### Formatting the data with `skip_header` and `autostrip`

In [481]:
raw_data_frmt = np.genfromtxt(pre_data, delimiter=';', skip_header=1, autostrip=True,encoding='latin1')
raw_data_frmt

array([[48010226.  ,         nan,    35000.  , ...,         nan,         nan,     9452.96],
       [57693261.  ,         nan,    30000.  , ...,         nan,         nan,     4679.7 ],
       [59432726.  ,         nan,    15000.  , ...,         nan,         nan,     1969.83],
       ...,
       [50415990.  ,         nan,    10000.  , ...,         nan,         nan,     2185.64],
       [46154151.  ,         nan,         nan, ...,         nan,         nan,     3199.4 ],
       [66055249.  ,         nan,    10000.  , ...,         nan,         nan,      301.9 ]])

> Skip the header of the data and the `autostrip` parameter is used to automatically remove (strip) leading and trailing whitespace from the data fields while reading the input text file.

### Checking a nan in a dataset

In [482]:
np.isnan(raw_data_frmt)

array([[False,  True, False, ...,  True,  True, False],
       [False,  True, False, ...,  True,  True, False],
       [False,  True, False, ...,  True,  True, False],
       ...,
       [False,  True, False, ...,  True,  True, False],
       [False,  True,  True, ...,  True,  True, False],
       [False,  True, False, ...,  True,  True, False]])

> From the output we know where is the data is nan or not by seeing it as a boolean value

### Checking howw many nan data is 

In [483]:
np.isnan(raw_data_frmt).sum()

88005

> From the output we know how many Nan data in a dataset

In [484]:
temp_fill = np.nanmax(raw_data_frmt) + 1
temp_mean = np.nanmean(raw_data_frmt, axis=0)

C:\Users\rafly.wicaksana\AppData\Local\Temp\ipykernel_12028\2555478099.py:2: RuntimeWarning: Mean of empty slice
  temp_mean = np.nanmean(raw_data_frmt, axis=0)


In [485]:
temp_mean

array([54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
            440.92,         nan,         nan,         nan,         nan,         nan,     3143.85])

> From the output we know where is the col/row that contains a nan (all the row/col is not contain a single number)
<br>
> The output that display a number, it col/row is containing atleast one numbers

In [486]:
temp_stats = np.array([np.nanmin(raw_data_frmt, axis=0),
                        temp_mean,
                       np.nanmax(raw_data_frmt, axis=0)])

C:\Users\rafly.wicaksana\AppData\Local\Temp\ipykernel_12028\4043172921.py:1: RuntimeWarning: All-NaN slice encountered
  temp_stats = np.array([np.nanmin(raw_data_frmt, axis=0),
C:\Users\rafly.wicaksana\AppData\Local\Temp\ipykernel_12028\4043172921.py:3: RuntimeWarning: All-NaN slice encountered
  np.nanmax(raw_data_frmt, axis=0)])


In [487]:
temp_stats

array([[  373332.  ,         nan,     1000.  ,         nan,     1000.  ,         nan,        6.  ,
              31.42,         nan,         nan,         nan,         nan,         nan,        0.  ],
       [54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
             440.92,         nan,         nan,         nan,         nan,         nan,     3143.85],
       [68616519.  ,         nan,    35000.  ,         nan,    35000.  ,         nan,       28.99,
            1372.97,         nan,         nan,         nan,         nan,         nan,    41913.62]])

#### Splitting Dataset

##### Searching where is the nan located

In [488]:
col_strings = np.argwhere(np.isnan(temp_mean))
col_strings


array([[ 1],
       [ 3],
       [ 5],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]], dtype=int64)

> Display the column that contains a string values based on the `temp_mean` type data

In [489]:
col_strings = np.argwhere(np.isnan(temp_mean)).squeeze()
col_strings

array([ 1,  3,  5,  8,  9, 10, 11, 12], dtype=int64)

> Squeeze will a uniform the array shape based on what slicing we use

In [490]:
col_numeric = np.argwhere(np.isnan(temp_mean) == False).squeeze()
col_numeric

array([ 0,  2,  4,  6,  7, 13], dtype=int64)

> Display the column that contains a numeric values based on the ! `temp_mean` data

In [491]:
loan_data_strings = np.genfromtxt(pre_data, delimiter=';', skip_header=1, autostrip=True, usecols=col_strings, dtype=str, encoding='latin1')
loan_data_strings

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [492]:
loan_data_numeric = np.genfromtxt(pre_data, 
                               delimiter=';', 
                               skip_header=1, 
                               autostrip=True, 
                               usecols=col_numeric,
                               filling_values=temp_fill, encoding='latin1')
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

#### Define the header

In [493]:
header_full = np.genfromtxt(pre_data, 
                               delimiter=';', 
                               skip_footer= raw_data_frmt.shape[0],
                               autostrip=True, 
                               dtype=str,
                               encoding='latin1')
header_full

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

#### Define the header based on the `col_string` and `col_numeric`

In [494]:
header_string, header_numeric = header_full[col_strings], header_full[col_numeric]
header_string

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [495]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [496]:
def checkpoint(file_name, checkpoint_header, checkpoint_data):
    np.savez(file_name, header = checkpoint_header, data = checkpoint_data)
    checkpoint_variable = np.load(file_name + '.npz')
    return (checkpoint_variable)

In [497]:
checkpoint_numeric =  checkpoint('checkpointNumeric', header_numeric, loan_data_numeric)
checkpoint_string = checkpoint('checkpointString', header_string, loan_data_strings)

In [498]:
np.array_equal(checkpoint_string['data'], loan_data_strings)

True

In [499]:
np.array_equal(checkpoint_numeric['data'], loan_data_numeric)

True

In [500]:
npz_data = 'checkpointData.npz'
load_npz = np.load(npz_data)
lst = load_npz.files
# for item in lst:
#     print('this is item',item)
#     print(load_npz[item])


# Manipulating Data

## Issue Date 

In [501]:
header_string

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [502]:
header_string[0] = 'issue_date'
header_string

array(['issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [503]:
loan_data_strings

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [504]:
np.unique(loan_data_strings[:,0])

array(['', 'Apr-15', 'Aug-15', 'Dec-15', 'Feb-15', 'Jan-15', 'Jul-15', 'Jun-15', 'Mar-15',
       'May-15', 'Nov-15', 'Oct-15', 'Sep-15'], dtype='<U69')

In [505]:
stripped_year = np.chararray.strip(loan_data_strings[:,0],'-15')

In [506]:
loan_data_strings[:,0] = stripped_year

In [507]:
loan_data_strings[:,0]

array(['May', '', 'Sep', ..., 'Jun', 'Apr', 'Dec'], dtype='<U69')

In [508]:
months = np.array(['','Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'])

In [509]:
for i in range(13):
    loan_data_strings[:,0] = np.where(loan_data_strings[:,0] == months[i],
                                     i,
                                     loan_data_strings[:,0])

In [510]:
display_T_issued_date = np.unique(loan_data_strings[:,0])
print(display_T_issued_date[np.newaxis].T)

[['0']
 ['1']
 ['10']
 ['11']
 ['12']
 ['2']
 ['3']
 ['4']
 ['5']
 ['6']
 ['7']
 ['8']
 ['9']]


In [511]:
np.transpose(loan_data_strings[:,0][np.newaxis])

array([['5'],
       ['0'],
       ['9'],
       ...,
       ['6'],
       ['4'],
       ['12']], dtype='<U69')

In [512]:
manipulated_T_issued_date = np.unique(loan_data_strings[:,0])
print(manipulated_T_issued_date[np.newaxis].T)

[['0']
 ['1']
 ['10']
 ['11']
 ['12']
 ['2']
 ['3']
 ['4']
 ['5']
 ['6']
 ['7']
 ['8']
 ['9']]


In [513]:
np.unique(loan_data_strings[:,0])

array(['0', '1', '10', '11', '12', '2', '3', '4', '5', '6', '7', '8', '9'], dtype='<U69')

## Loan Status

In [514]:
display_T_loan_status =  np.unique(loan_data_strings[:,1])
print(display_T_loan_status[np.newaxis].T)

[['']
 ['Charged Off']
 ['Current']
 ['Default']
 ['Fully Paid']
 ['In Grace Period']
 ['Issued']
 ['Late (16-30 days)']
 ['Late (31-120 days)']]


In [515]:
status_bad = np.array(['','Charged Off','Default','Late (31-120 days)'])

In [516]:
loan_data_strings[:,1] = np.where(np.isin(loan_data_strings[:,1], status_bad),
                                  0,1)

In [517]:
np.unique(loan_data_strings[:,1])

array(['0', '1'], dtype='<U69')

In [518]:
manipulated_T_loan_status =  np.unique(loan_data_strings[:,1])
print(manipulated_T_loan_status[np.newaxis].T)

[['0']
 ['1']]


## Term Months

In [519]:
header_string[2] = 'term_months'
header_string

array(['issue_date', 'loan_status', 'term_months', 'grade', 'sub_grade', 'verification_status',
       'url', 'addr_state'], dtype='<U19')

In [520]:
display_T_terms = np.unique(loan_data_strings[:,2])
print(loan_data_strings[:,2])
print(display_T_terms[np.newaxis].T)

['36 months' '36 months' '36 months' ... '36 months' '36 months' '36 months']
[['']
 ['36 months']
 ['60 months']]


In [521]:
stripped_month = np.chararray.strip(loan_data_strings[:,2],' months')
loan_data_strings[:,2] = stripped_month

In [522]:
loan_data_strings[:,2] = np.where(loan_data_strings[:,2] == '',
                                 '60',
                                 loan_data_strings[:,2])

In [523]:
manipulated_T_terms = np.unique(loan_data_strings[:,2])
print(loan_data_strings[:,2])
print(manipulated_T_terms[np.newaxis].T)

['36' '36' '36' ... '36' '36' '36']
[['36']
 ['60']]


## Grade

In [524]:
header_string

array(['issue_date', 'loan_status', 'term_months', 'grade', 'sub_grade', 'verification_status',
       'url', 'addr_state'], dtype='<U19')

In [525]:
print(loan_data_strings[:,3])
print(np.unique(loan_data_strings[:,3]))

['C' 'A' 'B' ... 'A' 'D' 'A']
['' 'A' 'B' 'C' 'D' 'E' 'F' 'G']


In [526]:
for i in np.unique(loan_data_strings[:,3])[1:]:
    loan_data_strings[:,4] = np.where((loan_data_strings[:,4] == '') & (loan_data_strings[:,3] == i),
                                      i+'5',
                                      loan_data_strings[:,4])

> Changing the lowest data of subgrade from `''` to readable data like `[grade]5`

In [527]:
gr = np.unique(loan_data_strings[:,3], return_counts=True)
sb_gr = np.unique(loan_data_strings[:,4], return_counts=True)
grade_transpose = np.concatenate((gr[0][:, np.newaxis], gr[1][:, np.newaxis]), axis=1)
sub_grade_transpose = np.concatenate((sb_gr[0][:,np.newaxis], sb_gr[1][:,np.newaxis]), axis=1)
print(grade_transpose)
print(sub_grade_transpose)

[['' '515']
 ['A' '1632']
 ['B' '2606']
 ['C' '2766']
 ['D' '1389']
 ['E' '816']
 ['F' '236']
 ['G' '40']]
[['' '9']
 ['A1' '285']
 ['A2' '278']
 ['A3' '239']
 ['A4' '323']
 ['A5' '592']
 ['B1' '509']
 ['B2' '517']
 ['B3' '530']
 ['B4' '553']
 ['B5' '633']
 ['C1' '629']
 ['C2' '567']
 ['C3' '586']
 ['C4' '564']
 ['C5' '577']
 ['D1' '391']
 ['D2' '267']
 ['D3' '250']
 ['D4' '255']
 ['D5' '288']
 ['E1' '235']
 ['E2' '162']
 ['E3' '171']
 ['E4' '139']
 ['E5' '160']
 ['F1' '94']
 ['F2' '52']
 ['F3' '34']
 ['F4' '43']
 ['F5' '24']
 ['G1' '19']
 ['G2' '10']
 ['G3' '3']
 ['G4' '7']
 ['G5' '5']]


In [528]:
loan_data_strings[:,4] = np.where(loan_data_strings[:,4] == '',
                                  'H1',
                                 loan_data_strings[:,4])

In [529]:
gr = np.unique(loan_data_strings[:,3], return_counts=True)
sb_gr = np.unique(loan_data_strings[:,4], return_counts=True)
grade_transpose = np.concatenate((gr[0][:, np.newaxis], gr[1][:, np.newaxis]), axis=1)
sub_grade_transpose = np.concatenate((sb_gr[0][:,np.newaxis], sb_gr[1][:,np.newaxis]), axis=1)
print(grade_transpose)
print(sub_grade_transpose)

[['' '515']
 ['A' '1632']
 ['B' '2606']
 ['C' '2766']
 ['D' '1389']
 ['E' '816']
 ['F' '236']
 ['G' '40']]
[['A1' '285']
 ['A2' '278']
 ['A3' '239']
 ['A4' '323']
 ['A5' '592']
 ['B1' '509']
 ['B2' '517']
 ['B3' '530']
 ['B4' '553']
 ['B5' '633']
 ['C1' '629']
 ['C2' '567']
 ['C3' '586']
 ['C4' '564']
 ['C5' '577']
 ['D1' '391']
 ['D2' '267']
 ['D3' '250']
 ['D4' '255']
 ['D5' '288']
 ['E1' '235']
 ['E2' '162']
 ['E3' '171']
 ['E4' '139']
 ['E5' '160']
 ['F1' '94']
 ['F2' '52']
 ['F3' '34']
 ['F4' '43']
 ['F5' '24']
 ['G1' '19']
 ['G2' '10']
 ['G3' '3']
 ['G4' '7']
 ['G5' '5']
 ['H1' '9']]


> Displaying data as transpose data 

In [530]:
loan_data_strings = np.delete(loan_data_strings, 3, axis=1)

In [531]:
loan_data_strings[:,3]

array(['C3', 'A5', 'B5', ..., 'A5', 'D2', 'A4'], dtype='<U69')

> Deleting the unused **Grade** data

In [532]:
header_string = np.delete(header_string, 3)

In [533]:
header_string

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

> Deleting the unused header of the **Grade**

> After deleting the data of grade and the header of grade, now the array index of 3 is now consisting of `sub_grade`

In [534]:
sb_gr_after = np.unique(loan_data_strings[:,3], return_counts=True)
sub_grade_aftertranspose = np.concatenate((sb_gr_after[0][:,np.newaxis], sb_gr_after[1][:,np.newaxis]), axis=1)
print(sub_grade_transpose)

[['A1' '285']
 ['A2' '278']
 ['A3' '239']
 ['A4' '323']
 ['A5' '592']
 ['B1' '509']
 ['B2' '517']
 ['B3' '530']
 ['B4' '553']
 ['B5' '633']
 ['C1' '629']
 ['C2' '567']
 ['C3' '586']
 ['C4' '564']
 ['C5' '577']
 ['D1' '391']
 ['D2' '267']
 ['D3' '250']
 ['D4' '255']
 ['D5' '288']
 ['E1' '235']
 ['E2' '162']
 ['E3' '171']
 ['E4' '139']
 ['E5' '160']
 ['F1' '94']
 ['F2' '52']
 ['F3' '34']
 ['F4' '43']
 ['F5' '24']
 ['G1' '19']
 ['G2' '10']
 ['G3' '3']
 ['G4' '7']
 ['G5' '5']
 ['H1' '9']]


> Displaying the data of the array index of 3 that previously **Grade**, that now is **sub_grade**

temp_mean

#### Converting the sub_grade to an integer using a dictionary

In [535]:
keys = list(np.unique(loan_data_strings[:,3]))
values = list(range(1, np.unique(loan_data_strings[:,3]).shape[0]+1))

In [536]:
dict_sub_grade = dict(zip(keys,values))

In [537]:
dict_sub_grade

{'A1': 1,
 'A2': 2,
 'A3': 3,
 'A4': 4,
 'A5': 5,
 'B1': 6,
 'B2': 7,
 'B3': 8,
 'B4': 9,
 'B5': 10,
 'C1': 11,
 'C2': 12,
 'C3': 13,
 'C4': 14,
 'C5': 15,
 'D1': 16,
 'D2': 17,
 'D3': 18,
 'D4': 19,
 'D5': 20,
 'E1': 21,
 'E2': 22,
 'E3': 23,
 'E4': 24,
 'E5': 25,
 'F1': 26,
 'F2': 27,
 'F3': 28,
 'F4': 29,
 'F5': 30,
 'G1': 31,
 'G2': 32,
 'G3': 33,
 'G4': 34,
 'G5': 35,
 'H1': 36}

> The dictionary is defined by
> <br>
> 1. Keys = list of the Grade value (A1,A2, etc)
> 2. Values = list of the range/length of Grade value 

In [538]:
for i in np.unique(loan_data_strings[:,3]):
    loan_data_strings[:,3] = np.where(loan_data_strings[:,3] == i, 
                                      dict_sub_grade[i],
                                     loan_data_strings[:,3])

In [539]:
np.unique(loan_data_strings[:,3])[np.newaxis].T

array([['1'],
       ['10'],
       ['11'],
       ['12'],
       ['13'],
       ['14'],
       ['15'],
       ['16'],
       ['17'],
       ['18'],
       ['19'],
       ['2'],
       ['20'],
       ['21'],
       ['22'],
       ['23'],
       ['24'],
       ['25'],
       ['26'],
       ['27'],
       ['28'],
       ['29'],
       ['3'],
       ['30'],
       ['31'],
       ['32'],
       ['33'],
       ['34'],
       ['35'],
       ['36'],
       ['4'],
       ['5'],
       ['6'],
       ['7'],
       ['8'],
       ['9']], dtype='<U69')

> Dictionary is applied to the `sub_grade` value, then displaying as a transpose

## Verification Status

In [540]:
header_string

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [541]:
loan_data_strings[:,4]

array(['Verified', 'Source Verified', 'Verified', ..., 'Source Verified', 'Source Verified', ''],
      dtype='<U69')

In [542]:
np.unique(loan_data_strings[:,4])

array(['', 'Not Verified', 'Source Verified', 'Verified'], dtype='<U69')

In [543]:
loan_data_strings[:,4] = np.where((loan_data_strings[:,4] == 'Source Verified') | (loan_data_strings[:,4] == 'Verified'),1,0
                                  )

In [544]:
loan_data_strings[:,4]

array(['1', '1', '1', ..., '1', '1', '0'], dtype='<U69')

In [545]:
np.unique(loan_data_strings[:,4])

array(['0', '1'], dtype='<U69')

## URL

In [546]:
loan_data_strings[:,5]

array(['https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', ...,
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249'], dtype='<U69')

In [547]:
np.chararray.strip(loan_data_strings[:,5], 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=')

chararray(['48010226', '57693261', '59432726', ..., '50415990', '46154151', '66055249'],
          dtype='<U69')

In [548]:
loan_data_strings[:,5] = np.chararray.strip(loan_data_strings[:,5], 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=')

In [549]:
loan_data_strings[:,5]

array(['48010226', '57693261', '59432726', ..., '50415990', '46154151', '66055249'], dtype='<U69')

In [550]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [551]:
loan_data_numeric[:,0]

array([48010226., 57693261., 59432726., ..., 50415990., 46154151., 66055249.])

In [552]:
loan_data_strings = np.delete(loan_data_strings, 5, axis = 1)
header_string = np.delete(header_string, 5)

In [553]:
header_string

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'addr_state'], dtype='<U19')

## State Address

In [554]:
loan_data_strings[:,5]

array(['CA', 'NY', 'PA', ..., 'CA', 'OH', 'IL'], dtype='<U69')

In [555]:
np.unique(loan_data_strings[:,5])

array(['', 'AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IL', 'IN',
       'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH',
       'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA',
       'VT', 'WA', 'WI', 'WV', 'WY'], dtype='<U69')

In [556]:
np.unique(loan_data_strings[:,5]).size

50

In [557]:
state_names, state_count = np.unique(loan_data_strings[:,5], return_counts=True)
states_count_sorted = np.argsort(-state_count)
state_names[states_count_sorted], state_count[states_count_sorted]

(array(['CA', 'NY', 'TX', 'FL', '', 'IL', 'NJ', 'GA', 'PA', 'OH', 'MI', 'NC', 'VA', 'MD', 'AZ',
        'WA', 'MA', 'CO', 'MO', 'MN', 'IN', 'WI', 'CT', 'TN', 'NV', 'AL', 'LA', 'OR', 'SC', 'KY',
        'KS', 'OK', 'UT', 'AR', 'MS', 'NH', 'NM', 'WV', 'HI', 'RI', 'MT', 'DE', 'DC', 'WY', 'AK',
        'NE', 'SD', 'VT', 'ND', 'ME'], dtype='<U69'),
 array([1336,  777,  758,  690,  500,  389,  341,  321,  320,  312,  267,  261,  242,  222,  220,
         216,  210,  201,  160,  156,  152,  148,  143,  143,  130,  119,  116,  108,  107,   84,
          84,   83,   74,   74,   61,   58,   57,   49,   44,   40,   28,   27,   27,   27,   26,
          25,   24,   17,   16,   10], dtype=int64))

In [558]:
loan_data_strings[:,5] = np.where(loan_data_strings[:,5] == '', 0, loan_data_strings[:,5])

In [559]:
np.unique(loan_data_strings[:,5],return_counts=True)

(array(['0', 'AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IL', 'IN',
        'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH',
        'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA',
        'VT', 'WA', 'WI', 'WV', 'WY'], dtype='<U69'),
 array([ 500,   26,  119,   74,  220, 1336,  201,  143,   27,   27,  690,  321,   44,  389,  152,
          84,   84,  116,  210,  222,   10,  267,  156,  160,   61,   28,  261,   16,   25,   58,
         341,   57,  130,  777,  312,   83,  108,  320,   40,  107,   24,  143,  758,   74,  242,
          17,  216,  148,   49,   27], dtype=int64))

In [560]:
states_west = np.array(['WA','OR','CA','NV','ID','MT','WY','UT','CO','AZ','NM','HI','AK'])
states_south = np.array(['TX','OK','AR','LA','MS','AL','TN','KY','FL','GA','SC','NC','VA','WV','MD','DE','DC'])
states_midwest = np.array(['ND','SD','NE','KS','MN','IA','MO','WI','IL','MI','IN','OH'])
states_east = np.array(['PA','NY','NJ','CT','MA','VT','NH','ME','RI'])

In [561]:
loan_data_strings[:,5] = np.where(np.isin(loan_data_strings[:,5], states_west), 1, loan_data_strings[:,5])
loan_data_strings[:,5] = np.where(np.isin(loan_data_strings[:,5], states_south), 2, loan_data_strings[:,5])
loan_data_strings[:,5] = np.where(np.isin(loan_data_strings[:,5], states_midwest), 3, loan_data_strings[:,5])
loan_data_strings[:,5] = np.where(np.isin(loan_data_strings[:,5], states_east), 4, loan_data_strings[:,5])

In [562]:
np.unique(loan_data_strings[:,5])[np.newaxis].T
# np.unique(loan_data_strings[:,5], return_counts=True)[np.newaxis].T

array([['0'],
       ['1'],
       ['2'],
       ['3'],
       ['4']], dtype='<U69')

In [563]:
loan_data_strings

array([['5', '1', '36', '13', '1', '1'],
       ['0', '1', '36', '5', '1', '4'],
       ['9', '1', '36', '10', '1', '4'],
       ...,
       ['6', '1', '36', '5', '1', '1'],
       ['4', '1', '36', '17', '1', '3'],
       ['12', '1', '36', '4', '0', '3']], dtype='<U69')

In [564]:
header_string[5] = 'address state'

In [565]:
header_string

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'address state'], dtype='<U19')

## Casting Loan Data String to Integer

In [566]:
loan_data_strings = loan_data_strings.astype(np.int32)

> Change the processed data from string to integer using casting

In [567]:
header_string

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'address state'], dtype='<U19')

In [568]:
loan_data_strings

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]])

In [569]:
checkpoint_string = checkpoint('Checkpoint-Strings', header_string, loan_data_strings)

In [570]:
checkpoint_string['header']

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'address state'], dtype='<U19')

> Making checkpoint for string data manipulation

In [571]:
checkpoint_string['data']

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]])

In [572]:
np.array_equal(header_string, checkpoint_string['header'])


True

In [573]:
np.array_equal(loan_data_strings, checkpoint_string['data'])

True

In [574]:
temp_fill

68616520.0

In [575]:
temp_stats

array([[  373332.  ,         nan,     1000.  ,         nan,     1000.  ,         nan,        6.  ,
              31.42,         nan,         nan,         nan,         nan,         nan,        0.  ],
       [54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
             440.92,         nan,         nan,         nan,         nan,         nan,     3143.85],
       [68616519.  ,         nan,    35000.  ,         nan,    35000.  ,         nan,       28.99,
            1372.97,         nan,         nan,         nan,         nan,         nan,    41913.62]])

In [576]:
print(temp_stats[0,col_numeric[2]])

1000.0


In [577]:
temp_mean

array([54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
            440.92,         nan,         nan,         nan,         nan,         nan,     3143.85])

In [578]:
temp_stats

array([[  373332.  ,         nan,     1000.  ,         nan,     1000.  ,         nan,        6.  ,
              31.42,         nan,         nan,         nan,         nan,         nan,        0.  ],
       [54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
             440.92,         nan,         nan,         nan,         nan,         nan,     3143.85],
       [68616519.  ,         nan,    35000.  ,         nan,    35000.  ,         nan,       28.99,
            1372.97,         nan,         nan,         nan,         nan,         nan,    41913.62]])

In [579]:
np.unique(loan_data_numeric[:,2])

array([    1000.,     1100.,     1175.,     1200.,     1225.,     1325.,     1400.,     1450.,
           1500.,     1600.,     1650.,     1675.,     1725.,     1750.,     1800.,     1875.,
           1900.,     1950.,     2000.,     2100.,     2200.,     2250.,     2300.,     2350.,
           2400.,     2500.,     2525.,     2600.,     2625.,     2650.,     2675.,     2700.,
           2775.,     2800.,     2875.,     2900.,     2950.,     3000.,     3050.,     3075.,
           3100.,     3150.,     3200.,     3225.,     3250.,     3275.,     3300.,     3325.,
           3350.,     3400.,     3450.,     3475.,     3500.,     3525.,     3550.,     3575.,
           3600.,     3650.,     3700.,     3725.,     3750.,     3800.,     3850.,     3875.,
           3900.,     3925.,     3950.,     3975.,     4000.,     4025.,     4100.,     4125.,
           4150.,     4175.,     4200.,     4225.,     4250.,     4275.,     4300.,     4325.,
           4350.,     4375.,     4400.,     4450.,

In [580]:
loan_data_numeric[:,2] = np.where(loan_data_numeric[:,2] == temp_fill, 
                                  temp_stats[0,col_numeric[2]], 
                                  loan_data_numeric[:,2])
loan_data_numeric[:,2]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.])

> Filling the funded_data using the `min` of the data 
<br> 
> We get the min from the `temp_data` we declare previously

In [581]:
np.isnan(loan_data_numeric[:,2]).sum()

0

> Check the data, is the nan of the funded data is still exists or not 

In [582]:
for i in [1,3,4,5]:
    loan_data_numeric[:,i] = np.where(loan_data_numeric[:,i] == temp_fill,
                                      temp_stats[2,col_numeric[i]],
                                      loan_data_numeric[:,i])

In [583]:
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  ,       28.99,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  ,       28.99,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  ,       28.99,     1372.97,     2185.64],
       [46154151.  ,    35000.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  ,       28.99,      309.97,      301.9 ]])

## Currency Change


In [584]:
EUR_USD = np.genfromtxt('dataset/EUR-USD.csv', delimiter=',', autostrip=True)

In [585]:
EUR_USD

array([[ nan,  nan,  nan,  nan,  nan],
       [1.21, 1.21, 1.11, 1.13, 0.  ],
       [1.13, 1.15, 1.12, 1.12, 0.  ],
       [1.12, 1.12, 1.05, 1.08, 0.  ],
       [1.07, 1.12, 1.05, 1.11, 0.  ],
       [1.12, 1.15, 1.08, 1.1 , 0.  ],
       [1.1 , 1.14, 1.09, 1.12, 0.  ],
       [1.11, 1.12, 1.08, 1.09, 0.  ],
       [1.1 , 1.17, 1.09, 1.13, 0.  ],
       [1.12, 1.15, 1.11, 1.13, 0.  ],
       [1.12, 1.15, 1.09, 1.1 , 0.  ],
       [1.1 , 1.11, 1.06, 1.06, 0.  ],
       [1.06, 1.11, 1.05, 1.09, 0.  ]])

In [586]:
EUR_USD = np.genfromtxt('dataset/EUR-USD.csv', delimiter=',', autostrip=True, dtype=str)
EUR_USD

array([['Open', 'High', 'Low', 'Close', 'Volume'],
       ['1.2098628282546997', '1.2098628282546997', '1.11055588722229', '1.1287955045700073', '0'],
       ['1.1287955045700073', '1.1484194993972778', '1.117680549621582', '1.1205360889434814',
        '0'],
       ['1.119795799255371', '1.1240400075912476', '1.0460032224655151', '1.0830246210098267',
        '0'],
       ['1.0741022825241089', '1.1247594356536865', '1.0521597862243652', '1.1114321947097778',
        '0'],
       ['1.1215037107467651', '1.145304799079895', '1.0821995735168457', '1.0960345268249512',
        '0'],
       ['1.095902442932129', '1.1428401470184326', '1.0888904333114624', '1.122296690940857', '0'],
       ['1.1134989261627197', '1.1219995021820068', '1.081270456314087', '1.0939244031906128',
        '0'],
       ['1.0969001054763794', '1.1705996990203857', '1.0850305557250977', '1.1340054273605347',
        '0'],
       ['1.1225990056991577', '1.1460003852844238', '1.1089695692062378', '1.1255937814712524

> We using a data so we skip the header and we use the coloumn of the 3rd index

In [587]:
EUR_USD = np.genfromtxt('dataset/EUR-USD.csv', delimiter=',', autostrip=True, skip_header=1, usecols=3)
EUR_USD

array([1.13, 1.12, 1.08, 1.11, 1.1 , 1.12, 1.09, 1.13, 1.13, 1.1 , 1.06, 1.09])

In [588]:
exchange_rate = loan_data_strings[:,0]
for i in range(1,13):
    exchange_rate = np.where(exchange_rate == i,
                            EUR_USD[i-1],
                            exchange_rate)
exchange_rate = np.where(exchange_rate == 0,
                         np.mean(EUR_USD),
                         exchange_rate)

In [589]:
np.unique(exchange_rate)[np.newaxis].T

array([[1.06],
       [1.08],
       [1.09],
       [1.09],
       [1.1 ],
       [1.1 ],
       [1.11],
       [1.11],
       [1.12],
       [1.12],
       [1.13],
       [1.13],
       [1.13]])

In [590]:
loan_data_numeric.shape

(10000, 6)

In [591]:
exchange_rate.shape

(10000,)

In [592]:
exchange_rate = np.reshape(exchange_rate, (10000,1))

In [593]:
exchange_rate

array([[1.1 ],
       [1.11],
       [1.13],
       ...,
       [1.12],
       [1.11],
       [1.09]])

In [594]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [595]:
loan_data_numeric = np.hstack((loan_data_numeric, exchange_rate))

In [596]:
header_numeric = np.concatenate((header_numeric, np.array(['exchange_rate'])))

> Adding new Header `called exchange_rate`

In [597]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate'],
      dtype='<U19')

In [598]:
column_dollar = np.array([1,2,4,5])

In [599]:

loan_data_numeric[:,[column_dollar]]

array([[[35000.  , 35000.  ,  1184.86,  9452.96]],

       [[30000.  , 30000.  ,   938.57,  4679.7 ]],

       [[15000.  , 15000.  ,   494.86,  1969.83]],

       ...,

       [[10000.  , 10000.  ,  1372.97,  2185.64]],

       [[35000.  , 10000.  ,   354.3 ,  3199.4 ]],

       [[10000.  , 10000.  ,   309.97,   301.9 ]]])

In [600]:
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  , ...,     1184.86,     9452.96,        1.1 ],
       [57693261.  ,    30000.  ,    30000.  , ...,      938.57,     4679.7 ,        1.11],
       [59432726.  ,    15000.  ,    15000.  , ...,      494.86,     1969.83,        1.13],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     1372.97,     2185.64,        1.12],
       [46154151.  ,    35000.  ,    10000.  , ...,      354.3 ,     3199.4 ,        1.11],
       [66055249.  ,    10000.  ,    10000.  , ...,      309.97,      301.9 ,        1.09]])

In [601]:
for i in column_dollar:
    loan_data_numeric = np.hstack((loan_data_numeric, np.reshape(loan_data_numeric[:,i] / loan_data_numeric[:,6], (10000,1))))

In [602]:
loan_data_numeric.shape

(10000, 11)

In [603]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate'],
      dtype='<U19')

In [604]:
header_additional = np.array([column_name + '_EUR' 
                              for column_name in header_numeric[column_dollar]])

In [605]:
header_additional

array(['loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U15')

In [606]:
header_numeric = np.concatenate((header_numeric, header_additional))

In [607]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate',
       'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U19')

In [608]:
header_numeric[np.newaxis].T

array([['id'],
       ['loan_amnt'],
       ['funded_amnt'],
       ['int_rate'],
       ['installment'],
       ['total_pymnt'],
       ['exchange_rate'],
       ['loan_amnt_EUR'],
       ['funded_amnt_EUR'],
       ['installment_EUR'],
       ['total_pymnt_EUR']], dtype='<U19')

In [609]:
header_numeric[column_dollar] = np.array([column_name + '_USD' 
                                          for column_name in header_numeric[column_dollar]])

In [610]:
header_numeric

array(['id', 'loan_amnt_USD', 'funded_amnt_USD', 'int_rate', 'installment_USD', 'total_pymnt_USD',
       'exchange_rate', 'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'],
      dtype='<U19')

In [611]:
column_index_order = [0,1,7,2,8,3,4,9,5,10,6]

In [612]:
header_numeric[column_index_order]

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
       'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate'],
      dtype='<U19')

In [613]:
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  , ...,    31933.3 ,     1081.04,     8624.69],
       [57693261.  ,    30000.  ,    30000.  , ...,    27132.46,      848.86,     4232.39],
       [59432726.  ,    15000.  ,    15000.  , ...,    13326.3 ,      439.64,     1750.04],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     8910.3 ,     1223.36,     1947.47],
       [46154151.  ,    35000.  ,    10000.  , ...,     8997.4 ,      318.78,     2878.63],
       [66055249.  ,    10000.  ,    10000.  , ...,     9145.8 ,      283.49,      276.11]])

In [614]:
header_numeric = header_numeric[column_index_order]

In [615]:
loan_data_numeric = loan_data_numeric[:,column_index_order]

In [616]:
header_numeric

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
       'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate'],
      dtype='<U19')

In [617]:
loan_data_numeric

array([[48010226.  ,    35000.  ,    31933.3 , ...,     9452.96,     8624.69,        1.1 ],
       [57693261.  ,    30000.  ,    27132.46, ...,     4679.7 ,     4232.39,        1.11],
       [59432726.  ,    15000.  ,    13326.3 , ...,     1969.83,     1750.04,        1.13],
       ...,
       [50415990.  ,    10000.  ,     8910.3 , ...,     2185.64,     1947.47,        1.12],
       [46154151.  ,    35000.  ,    31490.9 , ...,     3199.4 ,     2878.63,        1.11],
       [66055249.  ,    10000.  ,     9145.8 , ...,      301.9 ,      276.11,        1.09]])

In [618]:
loan_data_numeric[:,5] = loan_data_numeric[:,5] / 1000

In [619]:
loan_data_numeric[:,5]

array([0.01, 0.03, 0.03, ..., 0.03, 0.02, 0.03])

In [628]:
checkpoint_numeric = checkpoint('Checkpoint-Numeric', header_numeric, loan_data_numeric)

In [629]:
checkpoint_numeric['header'], checkpoint_numeric['data']

(array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
        'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate'],
       dtype='<U19'),
 array([[48010226.  ,    35000.  ,    31933.3 , ...,     9452.96,     8624.69,        1.1 ],
        [57693261.  ,    30000.  ,    27132.46, ...,     4679.7 ,     4232.39,        1.11],
        [59432726.  ,    15000.  ,    13326.3 , ...,     1969.83,     1750.04,        1.13],
        ...,
        [50415990.  ,    10000.  ,     8910.3 , ...,     2185.64,     1947.47,        1.12],
        [46154151.  ,    35000.  ,    31490.9 , ...,     3199.4 ,     2878.63,        1.11],
        [66055249.  ,    10000.  ,     9145.8 , ...,      301.9 ,      276.11,        1.09]]))

## Completing Dataset


In [630]:
checkpoint_string['data'].shape

(10000, 6)

In [631]:
checkpoint_numeric['data'].shape

(10000, 11)

In [638]:
loan_data = np.hstack((checkpoint_numeric['data'], checkpoint_string['data']))

In [639]:
loan_data.shape

(10000, 17)

In [640]:
np.isnan(loan_data).sum()

0

In [641]:
header_numeric

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
       'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate'],
      dtype='<U19')

In [642]:
header_full = np.hstack((checkpoint_numeric['header'], checkpoint_string['header']))

In [643]:
header_full

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
       'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate',
       'issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'address state'], dtype='<U19')

In [644]:
loan_data[np.argsort(loan_data[:,0])]

array([[  373332.  ,     9950.  ,     9038.08, ...,       21.  ,        0.  ,        1.  ],
       [  575239.  ,    12000.  ,    10900.2 , ...,       25.  ,        1.  ,        2.  ],
       [  707689.  ,    10000.  ,     8924.3 , ...,       13.  ,        1.  ,        0.  ],
       ...,
       [68614880.  ,     5600.  ,     5121.65, ...,        8.  ,        1.  ,        1.  ],
       [68615915.  ,     4000.  ,     3658.32, ...,       10.  ,        1.  ,        2.  ],
       [68616519.  ,    21600.  ,    19754.93, ...,        3.  ,        0.  ,        2.  ]])

In [645]:
loan_data = loan_data[np.argsort(loan_data[:,0])]

In [646]:
loan_data

array([[  373332.  ,     9950.  ,     9038.08, ...,       21.  ,        0.  ,        1.  ],
       [  575239.  ,    12000.  ,    10900.2 , ...,       25.  ,        1.  ,        2.  ],
       [  707689.  ,    10000.  ,     8924.3 , ...,       13.  ,        1.  ,        0.  ],
       ...,
       [68614880.  ,     5600.  ,     5121.65, ...,        8.  ,        1.  ,        1.  ],
       [68615915.  ,     4000.  ,     3658.32, ...,       10.  ,        1.  ,        2.  ],
       [68616519.  ,    21600.  ,    19754.93, ...,        3.  ,        0.  ,        2.  ]])

In [647]:
np.argsort(loan_data[:,0])

array([   0,    1,    2, ..., 9997, 9998, 9999], dtype=int64)

In [648]:
loan_data = np.vstack((header_full, loan_data))

In [649]:
loan_data

array([['id', 'loan_amnt_USD', 'loan_amnt_EUR', ..., 'sub_grade', 'verification_status',
        'address state'],
       ['373332.0', '9950.0', '9038.082814338286', ..., '21.0', '0.0', '1.0'],
       ['575239.0', '12000.0', '10900.20037910145', ..., '25.0', '1.0', '2.0'],
       ...,
       ['68614880.0', '5600.0', '5121.647851612413', ..., '8.0', '1.0', '1.0'],
       ['68615915.0', '4000.0', '3658.319894008867', ..., '10.0', '1.0', '2.0'],
       ['68616519.0', '21600.0', '19754.927427647883', ..., '3.0', '0.0', '2.0']], dtype='<U32')

In [650]:
np.savetxt('loan-data-preprocessed.csv', loan_data, fmt='%s', delimiter=';')