# Preprocessing Data

## Processing a raw data given a rules

In [85]:
import numpy as np

In [113]:
np.set_printoptions(suppress=True , linewidth=100, precision=2)

> Suppress is for disable a simplified out of bonds digit like `123e+`
<br>
> Linewidth is t set a width in a roow to a `100`
<br>
> Precision is used for a display 2 digit decimalals

### Loading a csv data and generate it using `genfromtxt`

In [119]:
pre_data = "dataset/loan-data.csv"

In [121]:
raw_data = np.genfromtxt(pre_data, delimiter=';')
raw_data

array([[        nan,         nan,         nan, ...,         nan,         nan,         nan],
       [48010226.  ,         nan,    35000.  , ...,         nan,         nan,     9452.96],
       [57693261.  ,         nan,    30000.  , ...,         nan,         nan,     4679.7 ],
       ...,
       [50415990.  ,         nan,    10000.  , ...,         nan,         nan,     2185.64],
       [46154151.  ,         nan,         nan, ...,         nan,         nan,     3199.4 ],
       [66055249.  ,         nan,    10000.  , ...,         nan,         nan,      301.9 ]])

### Formatting the data with `skip_header` and `autostrip`

In [124]:
raw_data_frmt = np.genfromtxt(pre_data, delimiter=';', skip_header=1, autostrip=True)
raw_data_frmt

array([[48010226.  ,         nan,    35000.  , ...,         nan,         nan,     9452.96],
       [57693261.  ,         nan,    30000.  , ...,         nan,         nan,     4679.7 ],
       [59432726.  ,         nan,    15000.  , ...,         nan,         nan,     1969.83],
       ...,
       [50415990.  ,         nan,    10000.  , ...,         nan,         nan,     2185.64],
       [46154151.  ,         nan,         nan, ...,         nan,         nan,     3199.4 ],
       [66055249.  ,         nan,    10000.  , ...,         nan,         nan,      301.9 ]])

> Skip the header of the data and the `autostrip` parameter is used to automatically remove (strip) leading and trailing whitespace from the data fields while reading the input text file.

### Checking a nan in a dataset

In [127]:
np.isnan(raw_data_frmt)

array([[False,  True, False, ...,  True,  True, False],
       [False,  True, False, ...,  True,  True, False],
       [False,  True, False, ...,  True,  True, False],
       ...,
       [False,  True, False, ...,  True,  True, False],
       [False,  True,  True, ...,  True,  True, False],
       [False,  True, False, ...,  True,  True, False]])

> From the output we know where is the data is nan or not by seeing it as a boolean value

### Checking howw many nan data is 

In [134]:
np.isnan(raw_data_frmt).sum()

88005

> From the output we know how many Nan data in a dataset

In [143]:
temp_fill = np.nanmax(raw_data_frmt) + 1
temp_mean = np.nanmean(raw_data_frmt, axis=0)

C:\Users\rafly.wicaksana\AppData\Local\Temp\ipykernel_20568\2555478099.py:2: RuntimeWarning: Mean of empty slice
  temp_mean = np.nanmean(raw_data_frmt, axis=0)


In [145]:
temp_mean

array([54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
            440.92,         nan,         nan,         nan,         nan,         nan,     3143.85])

> From the output we know where is the col/row that contains a nan (all the row/col is not contain a single number)
<br>
> The output that display a number, it col/row is containing atleast one numbers

In [104]:
temp_stats = np.array([np.min(raw_data_frmt, axis=0),
                        temp_mean,
                       np.max(raw_data_frmt, axis=0)])

In [106]:
temp_stats

array([[  373332.  ,         nan,         nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,         nan,         nan],
       [54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
             440.92,         nan,         nan,         nan,         nan,         nan,     3143.85],
       [68616519.  ,         nan,         nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,         nan,         nan]])

#### Splitting Dataset

##### Searching where is the nan located

In [198]:
col_strings = np.argwhere(np.isnan(temp_mean))
col_strings


array([[ 1],
       [ 3],
       [ 5],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]], dtype=int64)

> Display the column that contains a string values based on the `temp_mean` type data

In [240]:
col_strings = np.argwhere(np.isnan(temp_mean)).squeeze()
col_strings

array([ 1,  3,  5,  8,  9, 10, 11, 12], dtype=int64)

> Squeeze will a uniform the array shape based on what slicing we use

In [243]:
col_numeric = np.argwhere(np.isnan(temp_mean) == False).squeeze()
col_numeric

array([ 0,  2,  4,  6,  7, 13], dtype=int64)

> Display the column that contains a numeric values based on the ! `temp_mean` data

In [221]:
loan_data_strings = np.genfromtxt(pre_data, delimiter=';', skip_header=1, autostrip=True, usecols=col_strings, dtype=str)
loan_data_strings

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [229]:
loan_data_fill = np.genfromtxt(pre_data, 
                               delimiter=';', 
                               skip_header=1, 
                               autostrip=True, 
                               usecols=col_numeric,
                               filling_values=temp_fill)
loan_data_fill

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

In [233]:
header_full = np.genfromtxt(pre_data, 
                               delimiter=';', 
                               skip_footer= raw_data_frmt.shape[0],
                               autostrip=True, 
                               dtype=str)
header_full

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

In [235]:
header_string, header_numeric = header_full[col_strings], header_full[col_numeric]
header_string

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [237]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')