# Preprocessing Data

## Processing a raw data given a rules

In [367]:
import numpy as np

In [369]:
np.set_printoptions(suppress=True , linewidth=100, precision=2)

> Suppress is for disable a simplified out of bonds digit like `123e+`
<br>
> Linewidth is t set a width in a roow to a `100`
<br>
> Precision is used for a display 2 digit decimalals

### Loading a csv data and generate it using `genfromtxt`

In [373]:
pre_data = "dataset/loan-data.csv"

In [374]:
raw_data = np.genfromtxt(pre_data, delimiter=';')
raw_data

array([[        nan,         nan,         nan, ...,         nan,         nan,         nan],
       [48010226.  ,         nan,    35000.  , ...,         nan,         nan,     9452.96],
       [57693261.  ,         nan,    30000.  , ...,         nan,         nan,     4679.7 ],
       ...,
       [50415990.  ,         nan,    10000.  , ...,         nan,         nan,     2185.64],
       [46154151.  ,         nan,         nan, ...,         nan,         nan,     3199.4 ],
       [66055249.  ,         nan,    10000.  , ...,         nan,         nan,      301.9 ]])

### Formatting the data with `skip_header` and `autostrip`

In [376]:
raw_data_frmt = np.genfromtxt(pre_data, delimiter=';', skip_header=1, autostrip=True)
raw_data_frmt

array([[48010226.  ,         nan,    35000.  , ...,         nan,         nan,     9452.96],
       [57693261.  ,         nan,    30000.  , ...,         nan,         nan,     4679.7 ],
       [59432726.  ,         nan,    15000.  , ...,         nan,         nan,     1969.83],
       ...,
       [50415990.  ,         nan,    10000.  , ...,         nan,         nan,     2185.64],
       [46154151.  ,         nan,         nan, ...,         nan,         nan,     3199.4 ],
       [66055249.  ,         nan,    10000.  , ...,         nan,         nan,      301.9 ]])

> Skip the header of the data and the `autostrip` parameter is used to automatically remove (strip) leading and trailing whitespace from the data fields while reading the input text file.

### Checking a nan in a dataset

In [379]:
np.isnan(raw_data_frmt)

array([[False,  True, False, ...,  True,  True, False],
       [False,  True, False, ...,  True,  True, False],
       [False,  True, False, ...,  True,  True, False],
       ...,
       [False,  True, False, ...,  True,  True, False],
       [False,  True,  True, ...,  True,  True, False],
       [False,  True, False, ...,  True,  True, False]])

> From the output we know where is the data is nan or not by seeing it as a boolean value

### Checking howw many nan data is 

In [382]:
np.isnan(raw_data_frmt).sum()

88005

> From the output we know how many Nan data in a dataset

In [384]:
temp_fill = np.nanmax(raw_data_frmt) + 1
temp_mean = np.nanmean(raw_data_frmt, axis=0)

C:\Users\rafly.wicaksana\AppData\Local\Temp\ipykernel_20568\2555478099.py:2: RuntimeWarning: Mean of empty slice
  temp_mean = np.nanmean(raw_data_frmt, axis=0)


In [385]:
temp_mean

array([54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
            440.92,         nan,         nan,         nan,         nan,         nan,     3143.85])

> From the output we know where is the col/row that contains a nan (all the row/col is not contain a single number)
<br>
> The output that display a number, it col/row is containing atleast one numbers

In [387]:
temp_stats = np.array([np.min(raw_data_frmt, axis=0),
                        temp_mean,
                       np.max(raw_data_frmt, axis=0)])

In [388]:
temp_stats

array([[  373332.  ,         nan,         nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,         nan,         nan],
       [54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
             440.92,         nan,         nan,         nan,         nan,         nan,     3143.85],
       [68616519.  ,         nan,         nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,         nan,         nan]])

#### Splitting Dataset

##### Searching where is the nan located

In [391]:
col_strings = np.argwhere(np.isnan(temp_mean))
col_strings


array([[ 1],
       [ 3],
       [ 5],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]], dtype=int64)

> Display the column that contains a string values based on the `temp_mean` type data

In [393]:
col_strings = np.argwhere(np.isnan(temp_mean)).squeeze()
col_strings

array([ 1,  3,  5,  8,  9, 10, 11, 12], dtype=int64)

> Squeeze will a uniform the array shape based on what slicing we use

In [395]:
col_numeric = np.argwhere(np.isnan(temp_mean) == False).squeeze()
col_numeric

array([ 0,  2,  4,  6,  7, 13], dtype=int64)

> Display the column that contains a numeric values based on the ! `temp_mean` data

In [643]:
loan_data_strings = np.genfromtxt(pre_data, delimiter=';', skip_header=1, autostrip=True, usecols=col_strings, dtype=str)
loan_data_strings

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [398]:
loan_data_fill = np.genfromtxt(pre_data, 
                               delimiter=';', 
                               skip_header=1, 
                               autostrip=True, 
                               usecols=col_numeric,
                               filling_values=temp_fill)
loan_data_fill

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

#### Define the header

In [400]:
header_full = np.genfromtxt(pre_data, 
                               delimiter=';', 
                               skip_footer= raw_data_frmt.shape[0],
                               autostrip=True, 
                               dtype=str)
header_full

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

#### Define the header based on the `col_string` and `col_numeric`

In [402]:
header_string, header_numeric = header_full[col_strings], header_full[col_numeric]
header_string

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [403]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [404]:
def checkpoint(file_name, checkpoint_header, checkpoint_data):
    np.savez(file_name, header = checkpoint_header, data = checkpoint_data)
    checkpoint_variable = np.load(file_name + '.npz')
    return (checkpoint_variable)

In [405]:
checkpoint_numeric =  checkpoint('checkpointNumeric', header_numeric, loan_data_fill)
checkpoint_string = checkpoint('checkpointString', header_string, loan_data_strings)

In [406]:
np.array_equal(checkpoint_string['data'], loan_data_strings)

True

In [407]:
np.array_equal(checkpoint_numeric['data'], loan_data_fill)

True

In [408]:
npz_data = 'checkpointData.npz'
load_npz = np.load(npz_data)
lst = load_npz.files
# for item in lst:
#     print('this is item',item)
#     print(load_npz[item])


# Manipulating Data

## Issue Date 

In [645]:
header_string

array(['issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [647]:
header_string[0] = 'issue_date'
header_string

array(['issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [649]:
loan_data_strings

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [651]:
np.unique(loan_data_strings[:,0])

array(['', 'Apr-15', 'Aug-15', 'Dec-15', 'Feb-15', 'Jan-15', 'Jul-15', 'Jun-15', 'Mar-15',
       'May-15', 'Nov-15', 'Oct-15', 'Sep-15'], dtype='<U69')

In [653]:
stripped_year = np.chararray.strip(loan_data_strings[:,0],'-15')

In [655]:
loan_data_strings[:,0] = stripped_year

In [657]:
loan_data_strings[:,0]

array(['May', '', 'Sep', ..., 'Jun', 'Apr', 'Dec'], dtype='<U69')

In [659]:
months = np.array(['','Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'])

In [661]:
for i in range(13):
    loan_data_strings[:,0] = np.where(loan_data_strings[:,0] == months[i],
                                     i,
                                     loan_data_strings[:,0])

In [663]:
display_T_issued_date = np.unique(loan_data_strings[:,0])
print(display_T_issued_date[np.newaxis].T)

[['0']
 ['1']
 ['10']
 ['11']
 ['12']
 ['2']
 ['3']
 ['4']
 ['5']
 ['6']
 ['7']
 ['8']
 ['9']]


In [665]:
np.transpose(loan_data_strings[:,0][np.newaxis])

array([['5'],
       ['0'],
       ['9'],
       ...,
       ['6'],
       ['4'],
       ['12']], dtype='<U69')

In [667]:
manipulated_T_issued_date = np.unique(loan_data_strings[:,0])
print(manipulated_T_issued_date[np.newaxis].T)

[['0']
 ['1']
 ['10']
 ['11']
 ['12']
 ['2']
 ['3']
 ['4']
 ['5']
 ['6']
 ['7']
 ['8']
 ['9']]


In [668]:
np.unique(loan_data_strings[:,0])

array(['0', '1', '10', '11', '12', '2', '3', '4', '5', '6', '7', '8', '9'], dtype='<U69')

## Loan Status

In [671]:
display_T_loan_status =  np.unique(loan_data_strings[:,1])
print(display_T_loan_status[np.newaxis].T)

[['']
 ['Charged Off']
 ['Current']
 ['Default']
 ['Fully Paid']
 ['In Grace Period']
 ['Issued']
 ['Late (16-30 days)']
 ['Late (31-120 days)']]


In [673]:
status_bad = np.array(['','Charged Off','Default','Late (31-120 days)'])

In [675]:
loan_data_strings[:,1] = np.where(np.isin(loan_data_strings[:,1], status_bad),
                                  0,1)

In [677]:
np.unique(loan_data_strings[:,1])

array(['0', '1'], dtype='<U69')

In [689]:
manipulated_T_loan_status =  np.unique(loan_data_strings[:,1])
print(manipulated_T_loan_status[np.newaxis].T)

[['0']
 ['1']]


## Term Months

In [705]:
header_string[2] = 'term_months'
header_string

array(['issue_date', 'loan_status', 'term_months', 'grade', 'sub_grade', 'verification_status',
       'url', 'addr_state'], dtype='<U19')

In [691]:
display_T_terms = np.unique(loan_data_strings[:,2])
print(loan_data_strings[:,2])
print(display_T_terms[np.newaxis].T)

['36' '36' '36' ... '36' '36' '36']
[['']
 ['36']
 ['60']]


In [693]:
stripped_month = np.chararray.strip(loan_data_strings[:,2],' months')
loan_data_strings[:,2] = stripped_month

In [707]:
loan_data_strings[:,2] = np.where(loan_data_strings[:,2] == '',
                                 '60',
                                 loan_data_strings[:,2])

In [711]:
manipulated_T_terms = np.unique(loan_data_strings[:,2])
print(loan_data_strings[:,2])
print(manipulated_T_terms[np.newaxis].T)

['36' '36' '36' ... '36' '36' '36']
[['36']
 ['60']]


## Grade

In [723]:
header_string

array(['issue_date', 'loan_status', 'term_months', 'grade', 'sub_grade', 'verification_status',
       'url', 'addr_state'], dtype='<U19')

In [729]:
print(loan_data_strings[:,3])
print(np.unique(loan_data_strings[:,3]))

['C' 'A' 'B' ... 'A' 'D' 'A']
['' 'A' 'B' 'C' 'D' 'E' 'F' 'G']


In [731]:
for i in np.unique(loan_data_strings[:,3])[1:]:
    loan_data_strings[:,4] = np.where((loan_data_strings[:,4] == '') & (loan_data_strings[:,3] == i),
                                      i+'5',
                                      loan_data_strings[:,4])

> Changing the lowest data of subgrade from `''` to readable data like `[grade]5`

In [765]:
gr = np.unique(loan_data_strings[:,3], return_counts=True)
sb_gr = np.unique(loan_data_strings[:,4], return_counts=True)
grade_transpose = np.concatenate((gr[0][:, np.newaxis], gr[1][:, np.newaxis]), axis=1)
sub_grade_transpose = np.concatenate((sb_gr[0][:,np.newaxis], sb_gr[1][:,np.newaxis]), axis=1)
print(grade_transpose)
print(sub_grade_transpose)

[['' '515']
 ['A' '1632']
 ['B' '2606']
 ['C' '2766']
 ['D' '1389']
 ['E' '816']
 ['F' '236']
 ['G' '40']]
[['' '9']
 ['A1' '285']
 ['A2' '278']
 ['A3' '239']
 ['A4' '323']
 ['A5' '592']
 ['B1' '509']
 ['B2' '517']
 ['B3' '530']
 ['B4' '553']
 ['B5' '633']
 ['C1' '629']
 ['C2' '567']
 ['C3' '586']
 ['C4' '564']
 ['C5' '577']
 ['D1' '391']
 ['D2' '267']
 ['D3' '250']
 ['D4' '255']
 ['D5' '288']
 ['E1' '235']
 ['E2' '162']
 ['E3' '171']
 ['E4' '139']
 ['E5' '160']
 ['F1' '94']
 ['F2' '52']
 ['F3' '34']
 ['F4' '43']
 ['F5' '24']
 ['G1' '19']
 ['G2' '10']
 ['G3' '3']
 ['G4' '7']
 ['G5' '5']]


In [767]:
loan_data_strings[:,4] = np.where(loan_data_strings[:,4] == '',
                                  'H1',
                                 loan_data_strings[:,4])

In [769]:
gr = np.unique(loan_data_strings[:,3], return_counts=True)
sb_gr = np.unique(loan_data_strings[:,4], return_counts=True)
grade_transpose = np.concatenate((gr[0][:, np.newaxis], gr[1][:, np.newaxis]), axis=1)
sub_grade_transpose = np.concatenate((sb_gr[0][:,np.newaxis], sb_gr[1][:,np.newaxis]), axis=1)
print(grade_transpose)
print(sub_grade_transpose)

[['' '515']
 ['A' '1632']
 ['B' '2606']
 ['C' '2766']
 ['D' '1389']
 ['E' '816']
 ['F' '236']
 ['G' '40']]
[['A1' '285']
 ['A2' '278']
 ['A3' '239']
 ['A4' '323']
 ['A5' '592']
 ['B1' '509']
 ['B2' '517']
 ['B3' '530']
 ['B4' '553']
 ['B5' '633']
 ['C1' '629']
 ['C2' '567']
 ['C3' '586']
 ['C4' '564']
 ['C5' '577']
 ['D1' '391']
 ['D2' '267']
 ['D3' '250']
 ['D4' '255']
 ['D5' '288']
 ['E1' '235']
 ['E2' '162']
 ['E3' '171']
 ['E4' '139']
 ['E5' '160']
 ['F1' '94']
 ['F2' '52']
 ['F3' '34']
 ['F4' '43']
 ['F5' '24']
 ['G1' '19']
 ['G2' '10']
 ['G3' '3']
 ['G4' '7']
 ['G5' '5']
 ['H1' '9']]


> Displaying data as transpose data 

In [771]:
loan_data_strings = np.delete(loan_data_strings, 3, axis=1)

In [777]:
loan_data_strings[:,3]

array(['C3', 'A5', 'B5', ..., 'A5', 'D2', 'A4'], dtype='<U69')

> Deleting the unused **Grade** data

In [781]:
header_string = np.delete(header_string, 3)

In [783]:
header_string

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

> Deleting the unused header of the **Grade**

> After deleting the data of grade and the header of grade, now the array index of 3 is now consisting of `sub_grade`

In [790]:
sb_gr_after = np.unique(loan_data_strings[:,3], return_counts=True)
sub_grade_aftertranspose = np.concatenate((sb_gr_after[0][:,np.newaxis], sb_gr_after[1][:,np.newaxis]), axis=1)
print(sub_grade_transpose)

[['A1' '285']
 ['A2' '278']
 ['A3' '239']
 ['A4' '323']
 ['A5' '592']
 ['B1' '509']
 ['B2' '517']
 ['B3' '530']
 ['B4' '553']
 ['B5' '633']
 ['C1' '629']
 ['C2' '567']
 ['C3' '586']
 ['C4' '564']
 ['C5' '577']
 ['D1' '391']
 ['D2' '267']
 ['D3' '250']
 ['D4' '255']
 ['D5' '288']
 ['E1' '235']
 ['E2' '162']
 ['E3' '171']
 ['E4' '139']
 ['E5' '160']
 ['F1' '94']
 ['F2' '52']
 ['F3' '34']
 ['F4' '43']
 ['F5' '24']
 ['G1' '19']
 ['G2' '10']
 ['G3' '3']
 ['G4' '7']
 ['G5' '5']
 ['H1' '9']]


> Displaying the data of the array index of 3 that previously **Grade**, that now is **sub_grade**

temp_mean

#### Converting the sub_grade to an integer using a dictionary

In [798]:
keys = list(np.unique(loan_data_strings[:,3]))
values = list(range(1, np.unique(loan_data_strings[:,3]).shape[0]+1))

In [800]:
dict_sub_grade = dict(zip(keys,values))

In [802]:
dict_sub_grade

{'A1': 1,
 'A2': 2,
 'A3': 3,
 'A4': 4,
 'A5': 5,
 'B1': 6,
 'B2': 7,
 'B3': 8,
 'B4': 9,
 'B5': 10,
 'C1': 11,
 'C2': 12,
 'C3': 13,
 'C4': 14,
 'C5': 15,
 'D1': 16,
 'D2': 17,
 'D3': 18,
 'D4': 19,
 'D5': 20,
 'E1': 21,
 'E2': 22,
 'E3': 23,
 'E4': 24,
 'E5': 25,
 'F1': 26,
 'F2': 27,
 'F3': 28,
 'F4': 29,
 'F5': 30,
 'G1': 31,
 'G2': 32,
 'G3': 33,
 'G4': 34,
 'G5': 35,
 'H1': 36}

> The dictionary is defined by
> <br>
> 1. Keys = list of the Grade value (A1,A2, etc)
> 2. Values = list of the range/length of Grade value 

In [804]:
for i in np.unique(loan_data_strings[:,3]):
    loan_data_strings[:,3] = np.where(loan_data_strings[:,3] == i, 
                                      dict_sub_grade[i],
                                     loan_data_strings[:,3])

In [812]:
np.unique(loan_data_strings[:,3])[np.newaxis].T

array([['1'],
       ['10'],
       ['11'],
       ['12'],
       ['13'],
       ['14'],
       ['15'],
       ['16'],
       ['17'],
       ['18'],
       ['19'],
       ['2'],
       ['20'],
       ['21'],
       ['22'],
       ['23'],
       ['24'],
       ['25'],
       ['26'],
       ['27'],
       ['28'],
       ['29'],
       ['3'],
       ['30'],
       ['31'],
       ['32'],
       ['33'],
       ['34'],
       ['35'],
       ['36'],
       ['4'],
       ['5'],
       ['6'],
       ['7'],
       ['8'],
       ['9']], dtype='<U69')

> Dictionary is applied to the `sub_grade` value, then displaying as a transpose