# Import File 

In [64]:
text_file = 'text.txt'

In [68]:
file = open(text_file, mode = 'r').read()
file

'However, one should not forget the established organisation structure requires the clarification of new propositions. It should be noted that the established organisation structure represents an interesting experiment of further ways of development. However, one should not forget new model of the organisational activity allows to complete important implementation tasks of strengthening the democratic system.'

In [78]:
file2 = open(text_file, mode = 'r')
file2.read()

'However, one should not forget the established organisation structure requires the clarification of new propositions. It should be noted that the established organisation structure represents an interesting experiment of further ways of development. However, one should not forget new model of the organisational activity allows to complete important implementation tasks of strengthening the democratic system.'

In [150]:
file2.close()


## Import File Location

In [253]:
dryad = "dataset/Data_for_Dryad.xlsx"
example = "dataset/Lending-company.csv"

## Reading the data using pandas

In [231]:
import pandas as pd

In [216]:
pd.read_csv(example, index_col = "LoanID")

StringID    Product CustomerGender     Location    Region  \
LoanID                                                                 
1          LoanID_1  Product B         Female   Location 3  Region 2   
2          LoanID_2  Product D         Female   Location 6  Region 6   
3          LoanID_3  Product B           Male   Location 8  Region 3   
4          LoanID_4  Product A           Male  Location 26  Region 2   
5          LoanID_5  Product B         Female  Location 34  Region 3   
...             ...        ...            ...          ...       ...   
1039    LoanID_1039  Product B           Male  Location 73  Region 6   
1040    LoanID_1040  Product A           Male  Location 82  Region 1   
1041    LoanID_1041  Product A   NotSpecified  Location 11  Region 4   
1042    LoanID_1042  Product B         Female  Location 26  Region 6   
1043    LoanID_1043  Product A   NotSpecified  Location 94  Region 6   

        TotalPrice   StartDate  Deposit  DailyRate  TotalDaysYr  AmtPaid36  \
LoanID                                                                       
1          17600.0  04/07/2018     2200         45          365       3221   
2              NaN  02/01/2019     2200         45          365       3161   
3          16600.0  08/12/2016     1000         45          365       2260   
4          17600.0         NaN     2200         45          365       3141   
5          21250.0  28/10/2017     2200         55          365       3570   
...            ...         ...      ...        ...          ...        ...   
1039       17300.0  29/12/2018     2200         45          365       3251   
1040           NaN  28/03/2018     2200         45          365       4090   
1041       17300.0  26/04/2018     2200         45          365       4051   
1042       16300.0  25/10/2016     1000         45          365       1930   
1043       17300.0  15/05/2019     2200         45          365       4451   

        AmtPaid60  AmtPaid360        LoanStatus  
LoanID                                           
1            4166       14621            Active  
2            4096       16041            Active  
3            3205       16340               NaN  
4            4166       16321            Active  
5            4745       14720            Active  
...           ...         ...               ...  
1039         4743       16617  Finished Payment  
1040         5582       16617  Finished Payment  
1041         5143       16617  Finished Payment  
1042         3462       15617  Finished Payment  
1043         4743       16617  Finished Payment  

[1043 rows x 14 columns]

In [218]:
pd.read_excel(dryad, sheet_name=2, index_col = 'grid_code')

S   range.size  alkalinity_mean  bio1_mean  bio7_mean  \
grid_code                                                           
52          9  1812.222222      2014.000000   2.262675  21.898514   
53          9  1812.222222      1887.666667   0.967194  21.145729   
63          9  1812.222222      2093.000000   2.554747  22.776136   
64          9  1812.222222       788.900000   1.877027  22.067593   
73          8  2658.875000      6831.384615  -0.608028  29.039547   
...        ..          ...              ...        ...        ...   
9313       16  2321.687500      1846.863636  -0.393448  38.556437   
9314       16  2321.687500      2529.800000   0.659012  37.317298   
9321       50  1912.420000      7477.041667   5.307018  38.032869   
9324       41  1893.536585      3622.312500   6.081818  31.016071   
9325       37  1828.243243      2955.187500   6.096207  27.294943   

            bio12_mean         water      crop     urban  velocity_bio1.MEAN  \
grid_code                                                                      
52          663.751857  7.329346e+07  0.000000  0.093846        5.080150e+05   
53          652.876478  5.415485e+07  0.003200  0.000000        5.005323e+05   
63          562.928030  8.487558e+07  0.000000  0.000000        4.698171e+05   
64          570.042328  8.905863e+07  0.003077  0.000000        5.335722e+05   
73          670.980836  6.055762e+08  0.000000  0.000000        5.304648e+05   
...                ...           ...       ...       ...                 ...   
9313       1069.517241  2.817042e+08  0.000000  0.000000        2.694698e+05   
9314       1038.968434  2.717863e+08  0.000000  0.000000        3.185471e+06   
9321       1165.383275  2.293934e+07  6.668800  1.491200        3.156698e+06   
9324       1314.423077  1.043515e+08  2.940800  0.160000        3.093260e+06   
9325       1295.056322  1.666701e+08  0.033846  0.000000        3.129127e+06   

           velocity_bio12.MEAN  bio1_anon  bio12_anon             X  \
grid_code                                                             
52                2.289510e+04  -8.670367  -56.444165 -3.519811e+06   
53                6.139235e+03  -7.245765  -44.162193 -3.519811e+06   
63                1.879757e+04  -8.277824  -51.466492 -3.469812e+06   
64                6.134428e+03  -7.910360  -23.975661 -3.469811e+06   
73                9.347914e+04  -6.563401 -154.980836 -3.419817e+06   
...                        ...        ...         ...           ...   
9313              1.170364e+06 -28.160398 -751.594164  2.230261e+06   
9314              1.113545e+06 -27.525679 -689.801768  2.230260e+06   
9321              1.108239e+06 -27.122402 -568.998660  2.230256e+06   
9324              5.638788e+05 -25.863636 -454.786713  2.230255e+06   
9325              4.261018e+05 -25.396207 -383.056322  2.230255e+06   

                      Y  
grid_code                
52         3.079612e+06  
53         3.029612e+06  
63         3.079611e+06  
64         3.029612e+06  
73         3.579607e+06  
...                 ...  
9313       1.579619e+06  
9314       1.529620e+06  
9321       1.029623e+06  
9324       8.796240e+05  
9325       8.296243e+05  

[7131 rows x 15 columns]

## Import file location

In [10]:
example2 = "dataset/Lending-Company-Numeric-Data.csv"
example3 = "dataset/Lending-Company-Numeric-Data-NAN.csv"

## Reading data with numpy

In [13]:
import numpy as np

## Load txt 

#### Load txt will throw an error if the data that loaded in is contains a null or empty data

In [325]:
example2_loadtxt = np.loadtxt(example2, delimiter=',')
example2_loadtxt

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

## Gen from txt

#### Gen from txt will fill the empty or null data by empty string " " if the data that loaded in is empty

In [330]:
example3_gentxt = np.genfromtxt(example3, delimiter=';')
example3_gentxt

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [   nan,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [337]:
example3_gentxt_partial = np.genfromtxt(example3, delimiter=';', skip_header=2,skip_footer=2, usecols=(5,0,1))
example3_gentxt_partial


array([[15340.,  1000.,    40.],
       [15321.,  2000.,    40.],
       [13720.,  2000.,    50.],
       ...,
       [16600.,  2000.,    40.],
       [16600.,  2000.,    40.],
       [16600.,    nan,    40.]])

In [365]:
set_example3_setdtype = np.genfromtxt(example3, delimiter=';', dtype = "str", skip_header=2,skip_footer=2, usecols=(5,0,1))
set_example3_setdtype

array([['15340', '1000', '40'],
       ['15321', '2000', '40'],
       ['13720', '2000', '50'],
       ...,
       ['16600', '2000', '40'],
       ['16600', '2000', '40'],
       ['16600', '', '40']], dtype='<U5')

### Save data to json

#### Data can be saved using a `savetxt` and fill the required parameter like `fmt=` format of the file exported, `delimiter=` for the delimiter if its separator
> For the extension you can explicitly write in the exported filename in the first parameter

In [375]:
np.savetxt('example.json', set_example3_setdtype, fmt='%s', delimiter=',') 

In [380]:
np.savetxt('example.xlsx', set_example3_setdtype, fmt='%s', delimiter=',')

In [ ]:
loan_example = 